### ISSUE TITLE
Create demo of spinner animation

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/vanilla-design#13]
Use the existing Suru spinner, create a demo to see the spinner animation in action.

**Storyboard:**

![animations-spinner](https://cloud.githubusercontent.com/assets/223966/24047375/629c8ec0-0b1d-11e7-9fae-5ab69a2feff0.png)

**Comment by matthewpaulthomas** [comment]
I hadn’t seen this mockup until today. But for build.snapcraft.io, I specified that during a slow submission, a button’s label should be replaced by a centered spinner alone, rather than being replaced by a spinner and a different label.

This is because making a button wide enough to contain both the spinner and a label would mean either widening it after click (wobbling anything alongside it), or else making it unusually wide the rest of the time. A label that short would seldom communicate anything interesting anyway (“Create” → “Creating”, “Connect” → “Connecting”), but would sometimes be visible just for a fraction of a second, making you wonder whether you _had_ missed something.

**Comment by kwm14** [comment]
Closing as this issue as it's referenced and validated [here](https://github.com/ubuntudesign/vanilla-design/issues/42) in our bi-weekly working group.
