### ISSUE TITLE
Design page pagination component

### ISSUE THREAD

**Issue by kwm14** [ubuntudesign/vanilla-design#169]
We currently have [pagination](https://docs.vanillaframework.io/en/patterns/pagination) in Vanilla but it's only used for articles, we need to design a new variant of this pattern for pages.
- https://blog.ubuntu.com/ (scroll to bottom of page)

**Comment by kwm14** [comment]
Original issue found here: https://github.com/ubuntudesign/web-squad/issues/346#issuecomment-360803244

### Design (Michael)
![68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3539333535326266353161613263333035373830366438632f31653437333161382d616261372d346665362d613163322d636361646164303966643131](https://user-images.githubusercontent.com/17748020/35859830-7f58baee-0b39-11e8-9d53-db6f76d6517a.png)

**Comment by kwm14** [comment]
We also have two similar styles used on blog.ubuntu and snapcraft.io blog:

**blog.ubuntu.com**
- default state: font-size: `1rem`
- selected state: font-size: `1.5rem`, font-weight: `400`
![screen shot 2018-08-17 at 11 28 06](https://user-images.githubusercontent.com/17748020/44262874-850bf880-a214-11e8-9fc4-63816dddd032.png)

**snapcraft.io/blog**
- default state: font-size: `1rem`
- selected state: font-weight: `p-link--strong`

![screen shot 2018-08-17 at 11 30 57](https://user-images.githubusercontent.com/17748020/44263023-36ab2980-a215-11e8-86d6-ff5c1200a898.png)

**Comment by kwm14** [comment]
## First initial exploration
- Taking existing styles into consideration
- Explore using links and buttons
- Default state on the left and selected state on the right
- Will sync up with Claudio on Monday to discuss UX 😃 

### 001
![page-pagination-001](https://user-images.githubusercontent.com/17748020/44276055-53a82280-a23e-11e8-9726-1472f36a7571.png)

### 002
![page-pagination-002](https://user-images.githubusercontent.com/17748020/44276057-53a82280-a23e-11e8-8525-2ca3056da2d7.png)

### 003
![page-pagination-003](https://user-images.githubusercontent.com/17748020/44276058-5440b900-a23e-11e8-915b-0bfedde44b5b.png)

### 004
![page-pagination-004](https://user-images.githubusercontent.com/17748020/44276059-5440b900-a23e-11e8-8f57-fb24c0716364.png)

**Comment by kwm14** [comment]
@matthewpaulthomas could I get your opinion on the above explorations please? 😄

**Comment by matthewpaulthomas** [comment]
@kwm14 Happy to, but I think the designs needs fleshing out in a few ways:
- What do they look like when you’re on the first or last page? Presumably the Previous/Next control would be greyed out in some way, but the exact style might vary by design.
- What happens when there are more than five pages? Do you get an indication of how many pages there are, as in Michael’s design above? If so, what does the ellipsis look like?
- What do they look like when you’re on a page that isn’t in the first five? Do you still have quick access to the first page? If so, how?

Separately, I don’t understand what the “default state on the left” is for. In what kind of situation would this widget not show you which page you’re currently on?

If that default state isn’t applicable, you might be able to cover all these cases with two mockups per design:
- how it looks when you’re on page 1 of 3
- how it looks when you’re on page 7 of 138.

**Comment by kwm14** [comment]
@matthewpaulthomas thanks for your feedback 👍 I hadn't even thought about the scenarios you've listed above so you make valid points.

Agree default state isn't applicable, not sure what I was doing there! ha

I will create new mockups of my explorations based on your two scenarios 😄 which will cover all the points you raised above.

**Comment by kwm14** [comment]
## Updated designs
- taking feedback from @matthewpaulthomas above
- two variations of same design
   - how it looks when you’re on page 1 of 3
   - how it looks when you’re on page 7 of 138
- ellipsis styles to indicate more pages 
- @matthewpaulthomas ready for UX re-review 😄 

### 005
![page-pagination-005](https://user-images.githubusercontent.com/17748020/44409295-0687c180-a55a-11e8-9f90-0ff14e8a5589.png)

### 006
![page-pagination-006](https://user-images.githubusercontent.com/17748020/44409296-0687c180-a55a-11e8-8fbe-eadf4494887d.png)

### 007
![page-pagination-007](https://user-images.githubusercontent.com/17748020/44409297-07205800-a55a-11e8-8210-c50226b83ee7.png)

### 008
![page-pagination-008](https://user-images.githubusercontent.com/17748020/44409298-07205800-a55a-11e8-9f80-c2e6a3cc6516.png)

**Comment by anthonydillon** [comment]
I think 006 is much clearer to users.

**Comment by matthewpaulthomas** [comment]
005 and 008 are good in that they make the most common action — Next — the second-biggest element. They’d be even better if Next was at least as big as Previous.

With 006 and 008, the size of the buttons is more obvious, which probably makes them faster to click. The tradeoff is that it makes them much noisier than 005 and 007. Maybe the button borders could be lighter. (If they were, it would be better for the ellipses not to have borders at all, rather than trying to use an even lighter shade to indicate unclickability.)

006 and 007 are good in using arrows for Previous and Next, making the whole widget more recognizable at a glance.

007 and 008 are good in not relying on a small difference in font weight to show the current page. The darkness of 008 is probably overdoing it, though.

If it were up to me I wouldn’t choose one of these options, but pick out the good parts of each.

**Comment by kwm14** [comment]
## Updated design
- taking feedback from @matthewpaulthomas final UX review
- updated design taking elements from each design
- retained arrows for previous and Next 
- removed border from ellipsis
- updated selected state to reflect @spencerbygraves recent updates to button states [here](https://github.com/vanilla-framework/vanilla-framework/issues/1932) 
- ready for visual review

### 009
![page-pagination-009](https://user-images.githubusercontent.com/17748020/44727201-67227b80-aad1-11e8-9f26-9596a40f665b.png)

**Comment by anasereijo** [comment]
@kwm14 I really like the updated design (009). It's looking so much better than what we have at the moment 🥇
