### ISSUE TITLE
Button with spinner

### ISSUE THREAD

**Issue by bartaz** [ubuntudesign/vanilla-design#42]
In https://build.snapcraft.io we use spinner in the buttons that trigger some background action (calling web API and waiting for response):

<img width="478" alt="screen shot 2017-07-21 at 13 18 01" src="https://user-images.githubusercontent.com/83575/28461505-327b3f5e-6e17-11e7-9b8a-d6e96f192687.png">
<img width="481" alt="screen shot 2017-07-21 at 13 19 48" src="https://user-images.githubusercontent.com/83575/28461531-4d85d64c-6e17-11e7-82c7-ea382bdd479a.png">

Not to make the button change its size when spinner is displayed we are hiding button text and showing spinner in the centre of the button.
For more context see @matthewpaulthomas [comment](https://github.com/ubuntudesign/vanilla-design/issues/13#issuecomment-315734567) in "Create demo of spinner animation #13".

Currently Vanilla buttons don't provide any built-in means to show ongoing action (other then just disabling the button), and as screenshot in #13 suggests showing spinner in the button may be an option to consider to be part of the framework.

**Comment by Lukewh** [comment]
UX/ Design to decide on correct implementation.

**Comment by yaili** [comment]
Notes from working group:
- @matthewpaulthomas is going to find Ubuntu Touch guidelines on this subject that we could potentially adapt for Vanilla guidelines
- consider the option of a) displaying just icon/spinner or b) displaying icon + label - how could this be coded?
- will need design spec if/when added to Vanilla
- dashboard theme has a spinner already created

**Comment by matthewpaulthomas** [comment]
I’m not sure how broad “this subject” is: is it (a) avoiding width changes in buttons with spinners, (b) buttons with spinners in general, (c) spinners in general, (d) progress indicators in general, or (e) conveying progress in general?

- For (a) avoiding width changes in buttons, [I wrote](https://docs.google.com/document/d/19pLJ-wHRtB0T-1f6Z12foEYwIGElnXXU93oZ69uMCVY/edit#heading=h.ll5pox1az9wl):
  > For visual stability, a button’s **width** should stay the same while it is visible, unless this would cause its label to be ellipsized (which would be worse than instability). For example, a button that reads “Delete 9 Images” should widen if the label changes to “Delete 10 Images”, but should not narrow if the label reverts to “Delete 9 Images”.

  For a spinner to replace the label, rather than displacing it, is an obvious way to avoid the button getting wider *or* being ellipsized in this case. It does mean you lose context if you return to a long-churning page after several minutes. But if taking several minutes is at all likely, a spinner alone isn’t enough progress feedback anyway.

- For (b) buttons with spinners in general, I had meant to request this — plus disabling everything except “Cancel” in the dialog — as a standard toolkit behavior for dialogs: in my Bluetooth design I alluded to it as “[the standard progress state](https://wiki.ubuntu.com/Bluetooth?action=recall&rev=76#Pairing_manually)”. But it seems I didn’t get to it before Ubuntu Touch was retired. I did specify the behavior ad-hoc in several places; probably the most detailed is [connecting to a wi-fi network](https://wiki.ubuntu.com/Networking?action=recall&rev=324#wi-fi-connecting-dialog), but I hadn’t yet figured out the subtlety of waiting two seconds before the spinner appears.

  ![wi-fi-authentication-key-connecting phone](https://user-images.githubusercontent.com/19801137/29031331-c81bc850-7b85-11e7-8660-e823f30b826a.png)

- For (c) and (d) progress indicators in general, in 2016 I wrote [combined design guidelines for spinners and progress bars](https://docs.google.com/document/d/1lBnDb3NUjudl5bgJwkiC6lKEckcqxz5r_pKLwFQE3Bo/edit).

- For (e) conveying progress in general, in 2014 I wrote a broader and slightly fuzzier document “[Communicating progress](https://docs.google.com/document/d/1UP7pD-jtX_mIn7Mw3YBS2SbKgDcNnLoMlvnAhzArfko/edit)” that covers skeleton screens, progress text, and sound, as well as spinners and progress bars. It also includes an early iteration of the spinner-in-the-button design, with the text being dimmed instead of hidden altogether.

  ![spinner in a button](https://user-images.githubusercontent.com/19801137/29033265-61f42fd4-7b8c-11e7-87ee-78f0d4ba4ecf.png)

(Those last two documents are currently Canonical-only, but I could make them public if requested.)

**Comment by kwm14** [comment]
## Further development
@Caleb-Ellis has been working on action feedback on buttons in MAAS, his WIP PR can be found [here](https://github.com/vanilla-framework/vanilla-framework/pull/2027).

Demo of this in action can be found [here](https://vanilla-framework-vanilla-framework-pr-2027.run.demo.haus/vanilla-framework/examples/templates/action-feedback/).

![screenshot 2018-11-23 at 11 52 52](https://user-images.githubusercontent.com/17748020/48942193-55a51000-ef16-11e8-8486-19547e618cd9.png)

Currently being implemented in MAAS and RBAC, so once it's been pushed live we will take what @Caleb-Ellis has done and @deadlight can push it up to Vanilla 👍 💯 😄
